server:
  port: 7700

spring:
  application:
    name: seata-tm
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.88:3306/seata_order
    username: root
    password: root
  cloud:
    alibaba:
      seata:
        #自定义事务组名称需要与seata-server中的对应
        tx-service-group: my_test_tx_group
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        group: SEATA_GROUP
ribbon:
  ReadTimeout:  100000
  ConnectTimeout: 100000



mybatis:
  #mapper和dao接口不在同一个包写时，配xml的路径
  mapperLocations: classpath:mapper/*.xml
  #配上之后，xml的parameterType不用写全路径
  type-aliases-package: com.zhihao.domain    # 所有Entity别名类所在包